name: hybridyzer
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - rapids=24.08
  - python=3.10
  - numpy>=1.26.4,<2.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  - matplotlib>=3.7.0
  - pyarrow>=16.1.0,<16.2.0a0
  - pip

